/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class framexteam_wolframx_calculations_vectors_VectorLibraryJNI */

#ifndef _Included_framexteam_wolframx_calculations_vectors_VectorLibraryJNI
#define _Included_framexteam_wolframx_calculations_vectors_VectorLibraryJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     framexteam_wolframx_calculations_vectors_VectorLibraryJNI
 * Method:    sum
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_framexteam_wolframx_calculations_vectors_VectorLibraryJNI_sum
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     framexteam_wolframx_calculations_vectors_VectorLibraryJNI
 * Method:    sub
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_framexteam_wolframx_calculations_vectors_VectorLibraryJNI_sub
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     framexteam_wolframx_calculations_vectors_VectorLibraryJNI
 * Method:    scalarMul
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_framexteam_wolframx_calculations_vectors_VectorLibraryJNI_scalarMul
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     framexteam_wolframx_calculations_vectors_VectorLibraryJNI
 * Method:    vectorMul
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_framexteam_wolframx_calculations_vectors_VectorLibraryJNI_vectorMul
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     framexteam_wolframx_calculations_vectors_VectorLibraryJNI
 * Method:    numberMul
 * Signature: ([DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_framexteam_wolframx_calculations_vectors_VectorLibraryJNI_numberMul
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     framexteam_wolframx_calculations_vectors_VectorLibraryJNI
 * Method:    numberDiv
 * Signature: ([DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_framexteam_wolframx_calculations_vectors_VectorLibraryJNI_numberDiv
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     framexteam_wolframx_calculations_vectors_VectorLibraryJNI
 * Method:    abs
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_framexteam_wolframx_calculations_vectors_VectorLibraryJNI_abs
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     framexteam_wolframx_calculations_vectors_VectorLibraryJNI
 * Method:    angle
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_framexteam_wolframx_calculations_vectors_VectorLibraryJNI_angle
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
