/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class framexteam_wolframx_calculations_operations_equations_GaussSolverJNI */

#ifndef _Included_framexteam_wolframx_calculations_operations_equations_GaussSolverJNI
#define _Included_framexteam_wolframx_calculations_operations_equations_GaussSolverJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     framexteam_wolframx_calculations_operations_equations_GaussSolverJNI
 * Method:    solve
 * Signature: ([[D[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_framexteam_wolframx_calculations_operations_equations_GaussSolverJNI_solve
  (JNIEnv *, jclass, jobjectArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
